id: P008112
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1208
  title: བདེ་མཆོག་རིམ་ལྔའི་མན་ངག་།
  author: ''
  volumes:
    cdea64714b8b46749d38e597c04ccaa5:
      image_group_id: I1CZ2071
      title: ''
      volume_number: 1
      total_pages: 20
ebook_metadata:
  title: བདེ་མཆོག་རིམ་ལྔའི་མན་ངག་།
  author: ''
  sku: P008112
  cover: cover.jpg
  layers:
  - pagination
