id: P008112
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1CZ1208
  title: བདེ་མཆོག་རིམ་ལྔའི་མན་ངག་།
  author: ''
  volumes:
    a4baed6a3e8d44edb7141e69fa556033:
      image_group_id: I1CZ2071
      title: Volume 1 of bde mchog rim lnga'i man ngag
      volume_number: 1
      total_pages: 20
      base_file: v001.txt
