id: I508A0E5A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T22:27:58+00:00'
last_modified: '2022-06-09T04:35:16.338335+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1208
  title: བདེ་མཆོག་རིམ་ལྔའི་མན་ངག་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DAB8:
      image_group_id: I1CZ2071
      title: Volume 1 of bde mchog rim lnga'i man ngag
      total_pages: 20
      order: 1
      base_file: DAB8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
